live_config_reload = true

[window]
opacity = 0.8
padding = { x = 10, y = 10 }
dynamic_padding = false

[font]
#normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
size = 18
